CREATE DATABASE SUBWAYMAP;

USE SUBWAYMAP;

CREATE USER IF NOT EXISTS 'subway_user'@'%' IDENTIFIED BY 'subway_pw';
GRANT ALL PRIVILEGES ON SUBWAYMAP.* TO 'subway_user'@'%';

CREATE TABLE STATIONS
(
	ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
    STATUS     ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    UNIQUE KEY uk_stations_name (`NAME`)
) ENGINE = InnoDB;

CREATE TABLE `LINES`
(
	ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	STATUS     ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    UNIQUE KEY uk_lines_name (`NAME`)
) ENGINE = InnoDB;

CREATE TABLE LINE_STATIONS
(
	ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    LINE_ID    BIGINT NOT NULL,
    STATION_ID BIGINT NOT NULL,
    SEQ        INT NOT NULL,
    STATUS     ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    UNIQUE KEY UK_LS_LINE_SEQ (LINE_ID, SEQ),
    UNIQUE KEY UK_LS_LINE_STATION (LINE_ID, STATION_ID),
    CONSTRAINT FK_LS_LINE FOREIGN KEY (LINE_ID) REFERENCES `LINES` (ID),
    CONSTRAINT FK_LS_STATION FOREIGN KEY (STATION_ID) REFERENCES STATIONS (ID)
) ENGINE = InnoDB;

CREATE TABLE `SEGMENTS`
(
	ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    LINE_ID           BIGINT NOT NULL,
    BEFORE_STATION_ID BIGINT NOT NULL,
    AFTER_STATION_ID  BIGINT NOT NULL,
    DISTANCE          DOUBLE NOT NULL,
    SPEND_TIME        BIGINT NOT NULL,
    STATUS            ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT        DATETIME(6) NOT NULL,
    UPDATED_AT        DATETIME(6) NOT NULL,
    CONSTRAINT FK_SEGMENTS_LINE FOREIGN KEY (LINE_ID) REFERENCES `LINES` (ID),
    CONSTRAINT FK_SEGMENTS_BEFORE_STATION FOREIGN KEY (BEFORE_STATION_ID) REFERENCES STATIONS (ID),
    CONSTRAINT FK_SEGMENTS_AFTER_STATION FOREIGN KEY (AFTER_STATION_ID) REFERENCES STATIONS (ID)
) ENGINE = InnoDB;

CREATE TABLE `SEGMENT_HISTORIES`
(
	ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    SEGMENT_ID BIGINT NOT NULL,
    ACTION     ENUM('CREATE','UPDATE','REACTIVATE','DEACTIVATE') NOT NULL,
    CHANGED_AT DATETIME(6) NOT NULL,
    CONSTRAINT FK_SH_SEGMENTS FOREIGN KEY (SEGMENT_ID) REFERENCES SEGMENTS (ID)
) ENGINE = InnoDB;